
name: debugger
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Maximize build space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo swapoff -a
        sudo rm -f /mnt/swapfile

    - name: prepare
      run: |
        echo depot
        git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export DEPOT_TOOLS_DIR=$PWD/depot_tools
        PATH=$DEPOT_TOOLS_DIR:$DEPOT_TOOLS_DIR/python276_bin:$PATH

        echo .cipd
        git clone --depth 1 "https://github.com/kiwibrowser/dependencies" .cipd
        cp .cipd/.gclient .
        cp .cipd/.gclient_entries .

        echo src
        sudo apt-get update
        sudo apt-get install -y python openjdk-8-jdk-headless libncurses5 ccache
        sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
        git clone --depth 1 "https://github.com/$GITHUB_REPOSITORY" src
        cd src
        sudo bash install-build-deps.sh --no-chromeos-fonts
        build/linux/sysroot_scripts/install-sysroot.py --arch=i386
        build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
        keytool -genkey -v -keystore keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"
        gclient runhooks

        echo out
        mkdir -p out
        git clone https://github.com/AoEiuV020/kiwibrowser-arm64.git out/arm64
        gn gen out/arm64/

        echo keeplive
        touch /tmp/keepalive
    - name: Setup Debug Session
      env:   
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: csexton/debugger-action@master
